import type { Metadata } from "next";
import { Itim } from "next/font/google";
import "./globals.css";

const itim = Itim({
  weight: '400',
  subsets: ['thai'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Xelo Random",
  description: "Generated by Xelo",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${itim.className}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
